---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: minio
  namespace: tanzu-sync
spec:
  serviceAccountName: sync-sa
  fetch:
    - helmChart:
        name: bitnamicharts/minio
        version: 12.8.4
        repository:
          url: oci://registry-1.docker.io
          secretRef:
            name: dockercreds
  template:
    - helmTemplate:
        namespace: minio
        valuesFrom:
        - secretRef:
            name: minio-values
    - ytt:
        ignoreUnknownComments: true
        inline:
          paths:
            namespace.yaml: |
              ---
              apiVersion: v1
              kind: Namespace
              metadata:
                name: minio
  deploy:
    - kapp: {}