---
tap_install:
  values:
    profile: run
    tap_telemetry:
      installed_for_vmware_internal_use: "true"

    ceip_policy_disclosed: true
    shared:
      ingress_domain: "prod.h2o.grogscave.net"
      ingress_issuer: ""
      image_registry:
        project_path: "gcr.io/pa-cdelashmutt/tap-h2o/supply-chain"
      kubernetes_version: "1.25.12"
      kubernetes_distribution: openshift
    supply_chain: basic


    cnrs:
      default_tls_secret: default/default-cert
      domain_template: "{{- .Name}}-{{.Namespace -}}.{{.Domain}}"
      ingress:
        external:
          namespace: tanzu-system-ingress
        internal:
          namespace: tanzu-system-ingress
    contour:
      contour:
        replicas: 3
      infrastructure_provider: aws
      envoy:
        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: '*.prod.h2o.grogscave.net'      
        workload:
          type: Deployment
          replicas: 3

    

    appliveview_connector:
      backend:
        host: appliveview.dev.h2o.grogscave.net
        ingressEnabled: true

    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: clusters/prod/cluster-config/namespace-provisioner/namespaces
        url: https://github.com/cdelashmutt-pivotal/ice-clusters
      additional_sources:
        - git:
            ref: origin/main
            subPath: clusters/prod/cluster-config/namespace-provisioner/namespace-resources
            url: https://github.com/cdelashmutt-pivotal/ice-clusters
          path: _ytt_lib/namespace-resources
      import_data_values_secrets:
        - name: workload-git-auth
          namespace: tap-install
          create_export: true
      default_parameters:
        supply_chain_service_account:
          secrets:
          - git