apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  labels:
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: simple-java-web-app
    app.tanzu.vmware.com/deliverable-type: web
    apps.ice.com/prod: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    carto.run/cluster-template-name: deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/template-lifecycle: mutable
    carto.run/workload-name: simple-java-web-app
    carto.run/workload-namespace: qa
  name: simple-java-web-app
  namespace: prod
spec:
  params:
  - name: gitops_ssh_secret
    value: ""
  source:
    git:
      ref:
        branch: prod
      url: https://github.com/cdelashmutt-pivotal/ice-demo-gitops.git
    subPath: config/qa/simple-java-web-app