#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-contour-cluster-issuer
  annotations:
    kapp.k14s.io/change-group: "le-issuer"
spec:
  acme:
    email: cdelashmutt@vmware.com
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        route53:
          region: us-east-2
          accessKeyIDSecretRef:
            name: prod-route53-credentials-secret
            key: access-key-id
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key
---
apiVersion: v1
kind: Secret
metadata:
  name: prod-route53-credentials-secret
  namespace: cert-manager
type: Opaque
data:
  access-key-id: #@ base64.encode(data.values.aws.route53.accesskey)
  secret-access-key: #@ base64.encode(data.values.aws.route53.secretkey)
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-cert
  namespace: default
  annotations:
    kapp.k14s.io/change-group: "default-cert"
    kapp.k14s.io/change-rule.0: "upsert after upserting le-issuer"
    kapp.k14s.io/change-rule.1: "delete before deleting le-issuer"
spec:
  commonName: "*.dev.h2o.grogscave.net"
  dnsNames:
    - "*.dev.h2o.grogscave.net"
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: tls
  subject:
    organizations:
      - vmware
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: default-cert
  namespace: default
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting default-cert"
    kapp.k14s.io/change-rule.1: "delete before deleting default-cert"
spec:
  delegations:
    - secretName: tls
      targetNamespaces:
        - "*"
