---
tap_install:
  values:
    profile: full
    tap_telemetry:
      installed_for_vmware_internal_use: "true"

    excluded_packages:
    - learningcenter.tanzu.vmware.com
    - workshops.learningcenter.tanzu.vmware.com
    - policy.apps.tanzu.vmware.com

    package_overlays:
    - name: ootb-supply-chain-testing-scanning
      secrets:
      - name: ootb-testing-scanning-supply-chain-overlay

    ceip_policy_disclosed: true
    shared:
      ingress_domain: "dev.h2o.grogscave.net"
      ingress_issuer: ""
      image_registry:
        project_path: "gcr.io/pa-cdelashmutt/tap-h2o/supply-chain"
      kubernetes_version: "1.25.7"
    supply_chain: testing_scanning

    ootb_supply_chain_testing_scanning:
      external_delivery: false
      gitops:
        server_address: https://github.com
        repository_owner: cdelashmutt-pivotal
        repository_name: ice-demo-gitops
        commit_strategy: pull_request
        branch: main
        pull_request:
          server_kind: github
          commit_branch: ""
          pull_request_title: Delivery from sandbox Supply Chain
          pull_request_body: This is a candidate release for promotion

    accelerator:
      ingress:
        include: true
        enable_tls: true
      tls:
        namespace: default
        secret_name: default-cert

    appliveview:
      ingressEnabled: true
      tls:
        namespace: default
        secretName: default-cert
    
    appliveview_connector:
      activateSensitiveOperations: true

    cartographer:
      cartographer:
        concurrency:
          max_deliveries: 10
          max_runnables: 10
          max_workloads: 10
        resources:
          limits:
            cpu: "3"
            memory: 10Gi
          requests:
            cpu: 1.5
            memory: 10Gi
      conventions:
        resources:
          limits:
            memory: 600Mi
    cnrs:
      default_tls_secret: default/default-cert
      domain_template: "{{- .Name}}-{{.Namespace -}}.{{.Domain}}"
      ingress:
        external:
          namespace: tanzu-system-ingress
        internal:
          namespace: tanzu-system-ingress
    contour:
      contour:
        replicas: 3
      infrastructure_provider: aws
      envoy:
        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: '*.dev.h2o.grogscave.net'      
        workload:
          type: Deployment
          replicas: 3
    scanning:
      resources:
        limits:
          cpu: "500m"
          memory: 3Gi
        requests:
          cpu: 200m
          memory: 1Gi
          
    tap_gui:
      service_type: ClusterIP
      ingressEnabled: "true"
      tls:
        namespace: default
        secretName: default-cert
      app_config:
        app:
          support:
            url: https://tanzu.vmware.com/support
            items:
              - title: Contact ICE Support
                icon: email
                links:
                  - url: https://support.ice.com
                    title: ICE Support Page
              - title: Documentation
                icon: docs
                links:
                  - url: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/index.html
                    title: Tanzu Application Platform Documentation
        catalog:
          locations:
            - type: url
              target: https://github.com/cdelashmutt-pivotal/ice-clusters/blob/main/catalog/catalog-info.yaml
            - type: url
              target: https://github.com/tanzu-end-to-end/tap-workshop/blob/main/install/backstage/catalog-info.yaml
            - type: url
              target: https://github.com/cdelashmutt-pivotal/simple-java-web-app-accel/blob/main/catalog/catalog-info.yaml
        customize:
          default_route: '/docs/default/component/getting-started'
          custom_logo: 'iVBORw0KGgoAAAANSUhEUgAAADwAAAA8CAYAAAA6/NlyAAAA0XpUWHRSYXcgcHJvZmlsZSB0eXBlIGV4aWYAAHjabVHBDcMgDPx7io4APgfMOKRJpW7Q8WvASUPUkziMzzqMof3zftGjgaEkS9ZUUgoGKVK4WqBhoHaOQTp34OlanPN0CmwptMpx1OT1Rz6eBmOrFi0XI3WjuM5CEffXm5FfhNYRW7C5UXEj8BCiG9TxrJCK5usT1j3M0LGoEXL3Pk3uZ8k2vW2xJJh3RARjQEYDaAuEakExjlZkDSNbzFiMBcfMbCD/5hTaz3i3NP0EfsKUd9AXqcVjcRU2HPoAAAGEaUNDUElDQyBwcm9maWxlAAB4nH2RPUjDQBzFX1ulKhUHq4g4ZKhOdlGRjrUKRagQaoVWHUwu/YImDUmKi6PgWnDwY7Hq4OKsq4OrIAh+gLi6OCm6SIn/SwotYjw47se7e4+7d4C/UWGq2RUHVM0y0smEkM2tCsFX9CKEIQwjJjFTnxPFFDzH1z18fL2L8izvc3+OfiVvMsAnEMeZbljEG8Szm5bOeZ84zEqSQnxOPGnQBYkfuS67/Ma56LCfZ4aNTHqeOEwsFDtY7mBWMlTiGeKIomqU78+6rHDe4qxWaqx1T/7CUF5bWeY6zTEksYgliBAgo4YyKrAQpVUjxUSa9hMe/lHHL5JLJlcZjBwLqEKF5PjB/+B3t2ZhespNCiWA7hfb/hgHgrtAs27b38e23TwBAs/Aldb2VxtA7JP0eluLHAED28DFdVuT94DLHWDkSZcMyZECNP2FAvB+Rt+UAwZvgb41t7fWPk4fgAx1lboBDg6BiSJlr3u8u6ezt3/PtPr7AcbMcsi3q1P/AAANemlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNC40LjAtRXhpdjIiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iCiAgICB4bWxuczpzdEV2dD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlRXZlbnQjIgogICAgeG1sbnM6R0lNUD0iaHR0cDovL3d3dy5naW1wLm9yZy94bXAvIgogICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIgogICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iCiAgICB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iCiAgIHhtcE1NOkRvY3VtZW50SUQ9ImdpbXA6ZG9jaWQ6Z2ltcDowZjVkNTVjMC00Njg5LTQ4M2QtYWNmMi1iNGZiYWM0YjRlMjgiCiAgIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6YTU4ZTg1Y2YtMGMwMi00NDE2LTkwYzMtZWE0MzZhMDJmZGVkIgogICB4bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ9InhtcC5kaWQ6ZDY4MzJlYWQtNzg4Ni00OWVkLThjNzctZjlmMDAwYTI5MTY4IgogICBHSU1QOkFQST0iMi4wIgogICBHSU1QOlBsYXRmb3JtPSJNYWMgT1MiCiAgIEdJTVA6VGltZVN0YW1wPSIxNjk0NTUzOTQzODQ1NTg4IgogICBHSU1QOlZlcnNpb249IjIuMTAuMzQiCiAgIGRjOkZvcm1hdD0iaW1hZ2UvcG5nIgogICB0aWZmOk9yaWVudGF0aW9uPSIxIgogICB4bXA6Q3JlYXRvclRvb2w9IkdJTVAgMi4xMCIKICAgeG1wOk1ldGFkYXRhRGF0ZT0iMjAyMzowOToxMlQxNzoyNTo0My0wNDowMCIKICAgeG1wOk1vZGlmeURhdGU9IjIwMjM6MDk6MTJUMTc6MjU6NDMtMDQ6MDAiPgogICA8eG1wTU06SGlzdG9yeT4KICAgIDxyZGY6U2VxPgogICAgIDxyZGY6bGkKICAgICAgc3RFdnQ6YWN0aW9uPSJzYXZlZCIKICAgICAgc3RFdnQ6Y2hhbmdlZD0iLyIKICAgICAgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDo4NjQ5MWQwNS04MDQ4LTRmOTktODY0Mi0wYTBlZjMwNGM5MzkiCiAgICAgIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkdpbXAgMi4xMCAoTWFjIE9TKSIKICAgICAgc3RFdnQ6d2hlbj0iMjAyMy0wOS0xMlQxNzoyNTo0My0wNDowMCIvPgogICAgPC9yZGY6U2VxPgogICA8L3htcE1NOkhpc3Rvcnk+CiAgPC9yZGY6RGVzY3JpcHRpb24+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgCjw/eHBhY2tldCBlbmQ9InciPz4+A3lLAAAABmJLR0QAAAAAAAD5Q7t/AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5wkMFRkrrQJtkAAACBtJREFUaN7tm11oXNUWx3/nY5JMMpGZRKekmRYvJWmI0NKBaNAg8WIsGgNaSpAINgiKT1oq9+PhCqVCBC/c+9AXr09e4vgQKuJHpEW8D2J1bJoIgdSmAW1iaCfJtJ0mk6Qz55y97sPknJtJJl/2VmuYBYfZM7PX2eu/11p7rb3OPloinZWfUhl8uoawPUkDLCX8IViK+VMqw3/0AOnkAoZprtFdttC++8ixbQLVFfwxlcYsMXTSMwsYi2nsbapiU4P0NSi5T8dUIhimD1vAku1r1KZhosRC37ir9tvJKbfRLuSZgLkhYE1+O8jaL2hrGkqtjdxcT7O6z4em67mZ07agFe23a4sIZDNbA6zrGprh48juMnZU+LB/B74tIpiaxpyl+NdoFif34yorN9fgRtN1dlT4qC43f1fLU8BWS0ovHCrN9UzT1aySJcvR7mYNg65B1pGcWWva1nx4ObilteDuT6fIgdbWEVbfVEjQfldWndPwlgFvUyoCLgIuAi4CLgIuAi4CLgIuAi4CLgIuAi4CLgIuAt4mlCvxrKh6LH01tyFcDAQHMLQcTlMD5Tjo2xGwICh/gFJfCUo5aGg4jk1FlR9LFrYPYLfOWGbovLBTR7CXKtOCho4ti+ysKNl+GvYZGg33+tf8fxv6cK4oX8jUNU3bnoAL1eHdx77FOLzdybz7/E8KJBH/P747BlgplTf4eoIrpbw+hfoppdB1fU1eXddX8YnkniKu5LtjgNcScKVQmqZ5fR3HYX5+Hsuy0HWdsrIy/H5/wXut5J2bm2NhYQFN0wgEApSXl6NpmtfvjgJeXFxkZGQEwzDIZrPU1dVRVVWVN/hyrV26dImvvvqKs2fPMjIywvj4OMFgkLq6OqLRKC0tLbS0tFBeXp7H6zgOX3/9Nf39/XzzzTcMDw/j9/vZv38/jz32GIcOHWLv3r35wg1cScvfLmTkr/Epef3bhLz+bUL+FE/IXwZTkkhnRUREyeZIqVzPyclJWUrXBZB4PC4iIo7j5H2mUil588038/qudU1OToqIiGVZIiIyPT0t3d3dG/L19fXlyXhHNGwYBgDNzc3E43F8Pl+eKeq6ztTUFB0dHQwMDBCNRhkaGgLg5Zdfpqamhmw2y88//8z777/Piy++SG1tbe4ch2ly/fp1WltbuXDhAgD79u3j6NGj1NbWkk6nOXPmDO+++y7RaJTOzk4+++wz2tvbc+vKndDwlStXBJD6+noB5Pz58yIiYtu2iIgsLi5KR0eHANLU1CSAvPPOO5JIJDztu/0vXrwog4ODefc/duyYp8FXXnlFrl+/vkqW3t5eAaSxsVEASSQSIiJyRwG7g7mAXXOMxWICyCOPPCKAfP755xve252sc+fOeZNZX18vN27c8P53HMfrJyLy6quvehMTi8VERORXTTxM02R2dpY33niDSCTC2bNn6enp4cknn0RE8kLZ8rCjlPLc5JNPPvEWurfffptgMIht2xiGga7rGIaBbdsAHD582LvP6dOncZb2xL8qjY6O8uOPPxIOh/OEKhQz3fDmruypVIr33nuPyspKAB588EFvIldOLMDu3bsBCIfD9Pb2kkqlfv1Ma2xszPtsa2sjEolsmFG54WxmZobJyUkikQh+v5+TJ09SVlZW0DIMwyCVShEOhwkGg0xPT5NOpzd3bGlLRw83oEQi4SUKDQ0N+P3+TaeQN2/eBKC8vJzJyUneeuutTY05PT3tJTbrHkzLay6B/iW4l+e5lmWtMr3Nkuubtm0TiUR45pln8Pl8ax5Tcv0fIJPJcM8996yvYXNp1vXb1O5y7bn+BzAxMYFlWXlxej0qLS0FIJ1OE4lE6OnpobKy0svFNyODudYOWpRiaj6nDfcIoohQ7ffhM375DOzatctLFj788ENmZmbYuXPnuhsEV9iqqioAgsEgQ0NDpFIpKisrN9ycbLgfVkpQlsW/J27x99F5/jm6wD8upjl5WXHjlr3S4rdEDQ0Neeb8xRdf5O1uCrmD+3s4HKatrY2rV68CEI/HPd9cz52WL2r6euVOx8qisrdQ1i1028K6tXBba5eIsGfPHo4cOcLQ0BD19fV0d3czPDyMYRje7kYp5YF0d0RKKfx+P11dXczNzdHY2EhnZyfj4+Pe5Lk+W4h/0xUPpXKXg2zabNYix3HQdZ3XXnsNgEAgAMD+/fv58ssvyWaznoDuWDMzM/zwww+e0B0dHQAkk0kAnnrqKb7//nsvZruXy3/t2jUvFG5ue6gtb9weYF3XEREOHDhALBbj+eefp7GxEdu2efzxx2lvb+eJJ56gqqqKTCbDxMQEJ06coKuri1gshlKK6upq4vE4zc3NhMNhZmdniUajvPTSSzz88MOEQiGUUty8eZPx8XGOHz/Oc889xwcffJDz9cGr83Jqhg1f49E0wULnzw8Eua/CVzA0uwlCIpGgpqaGpqYmBgYGGBwcJBqNrlqYPvroIw4dOuT5pxsvC9HU1BThcBjHcTAMg++++47m5uYtxf8dO3ZgZh1F4N4A6aS7kBR+AUuUUFFWisL6X/F3DRN3F4mBgYFVsXf5xDz77LNcvnyZjz/+mL6+vlWAI5EITz/9NAcPHvTCmWslDz30EMlkkv7+fk6dOsWnn366So7W1lYeffRRWltbCQaDOUSbfRVPI3cy/oH7yij3GatKJysrHmNjY+i6jmVZ3H///YRCoVU8y7/Pz8+TTCZJp9OICH6/n1AoRCgU2rDOlclkSCaTzM7OYts2JSUlBAIBgsEgFRUVeXz/Bcc3W8+XnhDnAAAAAElFTkSuQmCC'
          custom_name: 'ICE Developer Portal'
        organization:
          name: ICE
        techdocs:
          builder: 'external'
          publisher:
            type: 'awsS3'
            awsS3:
              bucketName: 'techdocs-storage'
              accountId: minio
              region: us-east-1
              endpoint: http://minio.minio:9000
              s3ForcePathStyle: true
    metadata_store:
      ns_for_export_app_cert: "*"
      app_service_type: ClusterIP

    appliveview_connector:
      backend:
        host: appliveview.dev.h2o.grogscave.net
        ingressEnabled: true

    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: clusters/dev/cluster-config/namespace-provisioner/namespaces
        url: https://github.com/cdelashmutt-pivotal/ice-clusters
      additional_sources:
        - git:
            ref: origin/main
            subPath: clusters/dev/cluster-config/namespace-provisioner/namespace-resources
            url: https://github.com/cdelashmutt-pivotal/ice-clusters
          path: _ytt_lib/namespace-resources
      import_data_values_secrets:
        - name: workload-git-auth
          namespace: tap-install
          create_export: true
      default_parameters:
        supply_chain_service_account:
          secrets:
          - git

    local_source_proxy:
      repository: gcr.io/pa-cdelashmutt/tap-h2o/lsp
      push_secret:
        name: kp-default-repository-secret
        namespace: build-service
        create_export: true
      pull_secret:
        name: kp-default-repository-secret
        namespace: build-service
        create_export: true