---
tap_install:
  values:
    profile: full
    tap_telemetry:
      installed_for_vmware_internal_use: "true"

    excluded_packages:
    - learningcenter.tanzu.vmware.com
    - workshops.learningcenter.tanzu.vmware.com
    - policy.apps.tanzu.vmware.com

    package_overlays:
    - name: ootb-supply-chain-testing-scanning
      secrets:
      - name: ootb-testing-scanning-supply-chain-overlay

    ceip_policy_disclosed: true
    shared:
      ingress_domain: "dev.h2o.grogscave.net"
      ingress_issuer: ""
      image_registry:
        project_path: "gcr.io/pa-cdelashmutt/tap-h2o/supply-chain"
      kubernetes_version: "1.25.7"
    supply_chain: testing_scanning

    ootb_supply_chain_testing_scanning:
      external_delivery: false
      gitops:
        server_address: https://github.com
        repository_owner: cdelashmutt-pivotal
        repository_name: ice-demo-gitops
        commit_strategy: pull_request
        branch: main
        pull_request:
          server_kind: github
          commit_branch: ""
          pull_request_title: Delivery from sandbox Supply Chain
          pull_request_body: This is a candidate release for promotion

    accelerator:
      ingress:
        include: true
        enable_tls: true
      tls:
        namespace: default
        secret_name: default-cert

    appliveview:
      ingressEnabled: true
      tls:
        namespace: default
        secretName: default-cert
    
    appliveview_connector:
      activateSensitiveOperations: true

    cartographer:
      cartographer:
        concurrency:
          max_deliveries: 10
          max_runnables: 10
          max_workloads: 10
        resources:
          limits:
            cpu: "3"
            memory: 10Gi
          requests:
            cpu: 1.5
            memory: 10Gi
      conventions:
        resources:
          limits:
            memory: 600Mi
    cnrs:
      default_tls_secret: default/default-cert
      domain_template: "{{- .Name}}-{{.Namespace -}}.{{.Domain}}"
      ingress:
        external:
          namespace: tanzu-system-ingress
        internal:
          namespace: tanzu-system-ingress
    contour:
      contour:
        replicas: 3
      infrastructure_provider: aws
      envoy:
        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: '*.dev.h2o.grogscave.net'      
        workload:
          type: Deployment
          replicas: 3
    scanning:
      resources:
        limits:
          cpu: "500m"
          memory: 3Gi
        requests:
          cpu: 200m
          memory: 1Gi
          
    tap_gui:
      service_type: ClusterIP
      ingressEnabled: "true"
      tls:
        namespace: default
        secretName: default-cert
      app_config:
        catalog:
          locations:
            - type: url
              target: https://github.com/cdelashmutt-pivotal/ice-clusters/blob/main/catalog/catalog-info.yaml
            - type: url
              target: https://github.com/tanzu-end-to-end/tap-workshop/blob/main/install/backstage/catalog-info.yaml
            - type: url
              target: https://github.com/cdelashmutt-pivotal/simple-java-web-app-accel/blob/main/catalog/catalog-info.yaml
        customize:
          default_route: '/docs/default/component/getting-started'
        techdocs:
          builder: 'external'
          publisher:
            type: 'awsS3'
            awsS3:
              bucketName: 'techdocs-storage'
              accountId: minio
              region: us-east-1
              endpoint: http://minio.minio:9000
              s3ForcePathStyle: true
        kubernetes:
          clusterLocatorMethods:
          - type: 'config'
            clusters:
              - url: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}
                name: host
                authProvider: serviceAccount
                serviceAccountToken: ${KUBERNETES_SERVICE_ACCOUNT_TOKEN}
                skipTLSVerify: true
                skipMetricsLookup: false
    metadata_store:
      ns_for_export_app_cert: "*"
      app_service_type: ClusterIP

    appliveview_connector:
      backend:
        host: appliveview.dev.h2o.grogscave.net
        ingressEnabled: true

    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: clusters/dev/cluster-config/namespace-provisioner/namespaces
        url: https://github.com/cdelashmutt-pivotal/ice-clusters
      additional_sources:
        - git:
            ref: origin/main
            subPath: clusters/dev/cluster-config/namespace-provisioner/namespace-resources
            url: https://github.com/cdelashmutt-pivotal/ice-clusters
          path: _ytt_lib/namespace-resources
      import_data_values_secrets:
        - name: workload-git-auth
          namespace: tap-install
          create_export: true
      default_parameters:
        supply_chain_service_account:
          secrets:
          - git

    local_source_proxy:
      repository: gcr.io/pa-cdelashmutt/tap-h2o/lsp
      push_secret:
        name: kp-default-repository-secret
        namespace: build-service
        create_export: true
      pull_secret:
        name: kp-default-repository-secret
        namespace: build-service
        create_export: true