---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: ootb-testing-scanning-supply-chain
  namespace: tap-install
  annotations:
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: ootb-testing-scanning-supply-chain-overlay
spec:
  packageRef:
    refName: ootb-supply-chain-testing-scanning.tanzu.vmware.com
    versionSelection:
      constraints: ">0.13.8"
      prereleases: {}
  serviceAccountName: sync-sa
  values:
  - secretRef:
      name: ootb-testing-scanning-supply-chain-values
---
apiVersion: v1
kind: Secret
metadata:
  name: ootb-testing-scanning-supply-chain-values
  namespace: tap-install
type: Opaque
stringData:
  values.yml: |                                                                                                                                                                
    registry:                                                                                                                                                                  
      server: gcr.io
      repository: pa-cdelashmutt/tap-h2o/supply-chain/workloads
    external_delivery: false
    gitops:
      server_address: https://github.com
      repository_owner: cdelashmutt-pivotal
      repository_name: ice-demo-gitops
      commit_strategy: pull_request
      pull_request:
        server_kind: github
        commit_branch: supply_chain
        pull_request_title: Delivery from sandbox Supply Chain
        pull_request_body: This is a candidate release for promotion
---
apiVersion: v1
kind: Secret
metadata:
  name: ootb-testing-scanning-supply-chain-overlay
  namespace: tap-install
type: Opaque
stringData:
  overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "ClusterSupplyChain"}),expects=1
    ---
    spec:
      selector:
        #@overlay/match missing_ok=True
        apps.ice.com/prod: "true"